### ISSUE TITLE
Using a flask's liquid in a crafting recipe removes damage from the flask

### ISSUE THREAD

**Issue by MrHiTech123** [Gaelmare/WaterFlasks#21]
If you use a flask full of liquid as a tfc:fluid_item ingredient in a crafting recipe, this restores full durability to the flask (presumably by removing all nbt data from the flask?). Not sure if this is your problem to fix or TFC's though.

**Comment by WesCook** [comment]
Just wanted to confirm this bug is still present in the latest (v3.0.2).  An example craft is combining a partially-filled water flask with a single dirt block to craft mud.  This will fully heal the flask.

**Comment by Gaelmare** [comment]
Fix in progress. Any feature requests?
