### ISSUE TITLE
Clay apparently broke something

### ISSUE THREAD

**Issue by aliceingame** [Gaelmare/WaterFlasks#9]
Now might cause a crash in 135

java.lang.NoSuchMethodError: net.dries007.tfc.objects.recipes.ShapelessDamageRecipe: method <init>(Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/util/NonNullList;Lnet/minecraft/item/ItemStack;)V not found
    at tfctech.registry.TechRecipes.onRegisterCraftingRecipeEvent(TechRecipes.java:309)

**Comment by Gaelmare** [comment]
Fixed, thanks!
